INSERT INTO BUYING_STATIONS
(name, id_ubigeos, address, is_principal, created_by, updated_by)
VALUES
('ATP - LIMA', 1311,'AV. QUINTA AVENIDA MZA. C LOTE. 15 URB. LA CAPITANA HUACHIPA (ESQUINA ARCHIPIELAGO)', false, 1, 1),
('ATP - BAMBAMARCA', 1826, 'AV. FERNANDO BELAUNDE TERRY NRO. S/N C.P. BAMBAMARCA (A 2 CDRAS DE LA PLAZA DE ARMAS)', false, 1, 1),
('ATP - CAMPANILLA', 1789, 'JR. JULIO ROMERO CASTRO NRO. S/N',false , 1 ,1),
('ATP - EL DORADO', 1766, 'AV. SANTA ROSA MZA. 58 LOTE. 7 SEC. SECTOR 1 (ALTURA PTE EL DORADO)',false ,1 ,1),
('ATP - JUANJUI', 1788, 'CAR.JJ-TARAPOTO KM. 01 (FRENTE HOSPITAL IBAÑEZ)',false ,1 ,1),
('ATP - NUEVO PROGRESO',1827, 'JR. BELAUNDE TERRY MZA. 44 LOTE. 6 (A 100 METROS DE LA PLAZA DE ARMAS)',false , 1 ,1),
('ATP - PICHARI', 776, 'AV. LA CULTURA S/N NRO. S/N SEC. SECTOR OMAYA BAJA (SECTOR OMAYA BAJA)',false ,1, 1),
('ATP - PUERTO BERMUDEZ', 1576, 'AV. CAPITAN LARRIE MZA. 28 LOTE. 02 C.P. PUERTO BERMUDEZ (FRENTE AL MUNICIPIO)',false ,1 ,1), 
('ATP - SAN ALEJANDRO', 1885, 'CAR.FEDERICO BASADRE MZA. W3 LOTE. 3',false ,1 ,1),
('ATP - SAPOSOA', 1771, 'JR. PROLONGACION CHORRILLOS NRO. 245 SECTOR SAPOSOA (CARRETERA SAPOSOA PISCOYACU)',false ,1 ,1), 
('ATP - SATIPO', 1135, 'AV. ANTONIO RAYMONDI NRO. 289 URB. SATIPO (AL COSTADO DE LA FISCALIA)',false ,1 ,1),
('ATP - SELVA DE ORO', 1142, 'AV. INTEGRACION NRO. S/N C.P. CENTRO POBLADO SELVA DE ORO',false ,1 ,1),
('ATP - TABALOSOS', 1786, 'JR. LAMAS NRO. 432 BAR. PORVENIR',false ,1 ,1),
('ATP - TINGO MARIA', 966, 'JR. AUCAYACU NRO. 244 (CENTRO TINGO MARIA)',false ,1 ,1);